### ISSUE TITLE
显示比例问题

### ISSUE THREAD

**Issue by illuminatich** [steward-fu/gh_n900_emulator#1]
这个版本的PCSX-ReArmed确实比maemo社区的0.4要流畅一些，感谢发布！
不知道是我的编译环境有问题还是怎么回事，自己编译总是失败或者缺失功能。你发布的版本是全屏显示的，画面拉伸显得扁平，不知道能不能增加或者修改一个640x480的4:3全屏显示呢？能发布二进制最好了，代码我怕无法顺利编译成功……

**Comment by steward-fu** [comment]
binary, source都已更新，請重新抓一次

1. 已增加4：3選項，請從menu進去選擇
2. 你可以貼出編譯錯誤的訊息，我可以幫你看

**Comment by illuminatich** [comment]
virtualbox上的ubuntu安装了scratchbox和maemo SDK来编译的，因为磁盘空间不足出了不少问题，连整个系统全部清除了，改天再做一个新的虚拟机系统。
比较好奇你是怎样把sbox装在n900上的。

**Comment by illuminatich** [comment]
4:3的效果看起来非常好！

**Comment by steward-fu** [comment]
Sbox on n900: https://steward-fu.github.io/website/index.htm
 >> (SBox) 架設環境
